Added events and functions without methods
MrKahr/P3 pull request #7
Opened 2023-10-31 09:25 UTC by MrKahr

2023-10-31 12:18 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/function/AccountManager.java
Constructors should be the first "method". 
Generally, classes should follow: 1) fields, 2) constructors, 3) methods

2023-10-31 12:40 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/function/SessionManager.java
1) Maybe remove "setCurrentDate". We do not need to set the date as it is defined by the server clock. 
2) Do we need to construct a SessionManager object?
3) (Minor point, take lightly) Line 2 has two semicolons " ; ".

2023-10-31 12:43 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/events/DateSet.java
1) Nitpick. Line 8: "Constructor" is written funny

2023-10-31 13:04 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/events/ModuleSet.java
1) Question: Do we need the current getters and setters? The concrete strings (i.e. fields on line 5-6) are passed to the constructor when the event object is created, and since events are instantaneous, we should not need to get/set them.

2023-10-31 13:16 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/events/RewardsGiven.java
1) Constructors should be the first "method".
2) Should we have labels for getters/setters? Maybe change to one label "Methods".
3) Method "setDate" is unnecessary. This class is an event, which is instantanous, hence we only need to assign a date upon construction of the event object.

2023-10-31 13:19 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/events/RoleChanged.java
1) Constructors should be the first "method".
2) Should we have labels for getters/setters? Maybe change to one label "Methods".
3) Method "setDate" is unnecessary. This class is an event, which is instantanous, hence we only need to assign a date upon construction of the event object.

2023-10-31 13:20 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/events/UpdateSessionPlayerList.java
1) Constructors should be the first "method".
2) Should we have labels for getters/setters? Maybe change to one label "Methods".
3) Question: Do we need the current getters and setters? The concrete strings (i.e. fields on line 5-6) are passed to the constructor when the event object is created, and since events are instantaneous, we should not need to get/set them.

2023-10-31 13:27 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/users/Admin.java
1) Remember for later: add update method to add objects to the arraylists.

2023-10-31 13:36 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/users/Member.java
1) Should we have labels for getters/setters? Maybe change to one label "Methods".

2023-10-31 13:37 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/users/SuperAdmin.java
1) TODO: Add functionality to change admin role

2023-10-31 13:42 UTC, TheRealMorgenfrue commented on BackEndNServer/src/main/java/com/proj/model/users/Guest.java
1) Add label "Methods".
2) Maybe add a constructor? (Maybe to make it explicit/accomodate for future addons to the class)

2023-10-31 13:43 UTC, TheRealMorgenfrue requested changes
Please have a look at the comments for the individual files.

2023-11-01 09:27 UTC, MrKahr commented on BackEndNServer/src/main/java/com/proj/model/users/Guest.java
Comment resolved

2023-11-01 09:31 UTC, TheRealMorgenfrue approved these changes

2023-11-01 09:31 UTC, merged